/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as CoparentaliteRouteImport } from './routes/coparentalite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssuranceEmprunteurRouteImport } from './routes/assurance-emprunteur'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedEspaceRouteImport } from './routes/_authenticated/espace'
import { Route as AuthenticatedEspaceIndexRouteImport } from './routes/_authenticated/espace.index'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as AuthenticatedEspaceUtilisateursRouteImport } from './routes/_authenticated/espace.utilisateurs'
import { Route as AuthenticatedEspaceTachesRouteImport } from './routes/_authenticated/espace.taches'
import { Route as AuthenticatedEspaceCommissionsRouteImport } from './routes/_authenticated/espace.commissions'
import { Route as AuthenticatedEspaceDossiersIndexRouteImport } from './routes/_authenticated/espace.dossiers.index'
import { Route as AuthenticatedEspaceCompagniesIndexRouteImport } from './routes/_authenticated/espace.compagnies.index'
import { Route as AuthenticatedEspaceClientsIndexRouteImport } from './routes/_authenticated/espace.clients.index'
import { Route as AuthenticatedEspaceDossiersIdRouteImport } from './routes/_authenticated/espace.dossiers.$id'
import { Route as AuthenticatedEspaceContratsIdRouteImport } from './routes/_authenticated/espace.contrats.$id'
import { Route as AuthenticatedEspaceCompagniesIdRouteImport } from './routes/_authenticated/espace.compagnies.$id'
import { Route as AuthenticatedEspaceClientsIdRouteImport } from './routes/_authenticated/espace.clients.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const CoparentaliteRoute = CoparentaliteRouteImport.update({
  id: '/coparentalite',
  path: '/coparentalite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceEmprunteurRoute = AssuranceEmprunteurRouteImport.update({
  id: '/assurance-emprunteur',
  path: '/assurance-emprunteur',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceRoute = AuthenticatedEspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEspaceIndexRoute =
  AuthenticatedEspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceUtilisateursRoute =
  AuthenticatedEspaceUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceTachesRoute =
  AuthenticatedEspaceTachesRouteImport.update({
    id: '/taches',
    path: '/taches',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceCommissionsRoute =
  AuthenticatedEspaceCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceDossiersIndexRoute =
  AuthenticatedEspaceDossiersIndexRouteImport.update({
    id: '/dossiers/',
    path: '/dossiers/',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceCompagniesIndexRoute =
  AuthenticatedEspaceCompagniesIndexRouteImport.update({
    id: '/compagnies/',
    path: '/compagnies/',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceClientsIndexRoute =
  AuthenticatedEspaceClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceDossiersIdRoute =
  AuthenticatedEspaceDossiersIdRouteImport.update({
    id: '/dossiers/$id',
    path: '/dossiers/$id',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceContratsIdRoute =
  AuthenticatedEspaceContratsIdRouteImport.update({
    id: '/contrats/$id',
    path: '/contrats/$id',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceCompagniesIdRoute =
  AuthenticatedEspaceCompagniesIdRouteImport.update({
    id: '/compagnies/$id',
    path: '/compagnies/$id',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceClientsIdRoute =
  AuthenticatedEspaceClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/coparentalite': typeof CoparentaliteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/espace': typeof AuthenticatedEspaceRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/espace/commissions': typeof AuthenticatedEspaceCommissionsRoute
  '/espace/taches': typeof AuthenticatedEspaceTachesRoute
  '/espace/utilisateurs': typeof AuthenticatedEspaceUtilisateursRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/espace/': typeof AuthenticatedEspaceIndexRoute
  '/espace/clients/$id': typeof AuthenticatedEspaceClientsIdRoute
  '/espace/compagnies/$id': typeof AuthenticatedEspaceCompagniesIdRoute
  '/espace/contrats/$id': typeof AuthenticatedEspaceContratsIdRoute
  '/espace/dossiers/$id': typeof AuthenticatedEspaceDossiersIdRoute
  '/espace/clients/': typeof AuthenticatedEspaceClientsIndexRoute
  '/espace/compagnies/': typeof AuthenticatedEspaceCompagniesIndexRoute
  '/espace/dossiers/': typeof AuthenticatedEspaceDossiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/coparentalite': typeof CoparentaliteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/espace/commissions': typeof AuthenticatedEspaceCommissionsRoute
  '/espace/taches': typeof AuthenticatedEspaceTachesRoute
  '/espace/utilisateurs': typeof AuthenticatedEspaceUtilisateursRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/espace': typeof AuthenticatedEspaceIndexRoute
  '/espace/clients/$id': typeof AuthenticatedEspaceClientsIdRoute
  '/espace/compagnies/$id': typeof AuthenticatedEspaceCompagniesIdRoute
  '/espace/contrats/$id': typeof AuthenticatedEspaceContratsIdRoute
  '/espace/dossiers/$id': typeof AuthenticatedEspaceDossiersIdRoute
  '/espace/clients': typeof AuthenticatedEspaceClientsIndexRoute
  '/espace/compagnies': typeof AuthenticatedEspaceCompagniesIndexRoute
  '/espace/dossiers': typeof AuthenticatedEspaceDossiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/coparentalite': typeof CoparentaliteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/espace': typeof AuthenticatedEspaceRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/espace/commissions': typeof AuthenticatedEspaceCommissionsRoute
  '/_authenticated/espace/taches': typeof AuthenticatedEspaceTachesRoute
  '/_authenticated/espace/utilisateurs': typeof AuthenticatedEspaceUtilisateursRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/_authenticated/espace/': typeof AuthenticatedEspaceIndexRoute
  '/_authenticated/espace/clients/$id': typeof AuthenticatedEspaceClientsIdRoute
  '/_authenticated/espace/compagnies/$id': typeof AuthenticatedEspaceCompagniesIdRoute
  '/_authenticated/espace/contrats/$id': typeof AuthenticatedEspaceContratsIdRoute
  '/_authenticated/espace/dossiers/$id': typeof AuthenticatedEspaceDossiersIdRoute
  '/_authenticated/espace/clients/': typeof AuthenticatedEspaceClientsIndexRoute
  '/_authenticated/espace/compagnies/': typeof AuthenticatedEspaceCompagniesIndexRoute
  '/_authenticated/espace/dossiers/': typeof AuthenticatedEspaceDossiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/assurance-emprunteur'
    | '/auth'
    | '/contact'
    | '/coparentalite'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/espace'
    | '/blog/$slug'
    | '/blog/'
    | '/espace/commissions'
    | '/espace/taches'
    | '/espace/utilisateurs'
    | '/api/public/leads'
    | '/espace/'
    | '/espace/clients/$id'
    | '/espace/compagnies/$id'
    | '/espace/contrats/$id'
    | '/espace/dossiers/$id'
    | '/espace/clients/'
    | '/espace/compagnies/'
    | '/espace/dossiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/assurance-emprunteur'
    | '/auth'
    | '/contact'
    | '/coparentalite'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog'
    | '/espace/commissions'
    | '/espace/taches'
    | '/espace/utilisateurs'
    | '/api/public/leads'
    | '/espace'
    | '/espace/clients/$id'
    | '/espace/compagnies/$id'
    | '/espace/contrats/$id'
    | '/espace/dossiers/$id'
    | '/espace/clients'
    | '/espace/compagnies'
    | '/espace/dossiers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/assurance-emprunteur'
    | '/auth'
    | '/contact'
    | '/coparentalite'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/sitemap.xml'
    | '/_authenticated/espace'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/espace/commissions'
    | '/_authenticated/espace/taches'
    | '/_authenticated/espace/utilisateurs'
    | '/api/public/leads'
    | '/_authenticated/espace/'
    | '/_authenticated/espace/clients/$id'
    | '/_authenticated/espace/compagnies/$id'
    | '/_authenticated/espace/contrats/$id'
    | '/_authenticated/espace/dossiers/$id'
    | '/_authenticated/espace/clients/'
    | '/_authenticated/espace/compagnies/'
    | '/_authenticated/espace/dossiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AssuranceEmprunteurRoute: typeof AssuranceEmprunteurRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CoparentaliteRoute: typeof CoparentaliteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coparentalite': {
      id: '/coparentalite'
      path: '/coparentalite'
      fullPath: '/coparentalite'
      preLoaderRoute: typeof CoparentaliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-emprunteur': {
      id: '/assurance-emprunteur'
      path: '/assurance-emprunteur'
      fullPath: '/assurance-emprunteur'
      preLoaderRoute: typeof AssuranceEmprunteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/': {
      id: '/_authenticated/espace/'
      path: '/'
      fullPath: '/espace/'
      preLoaderRoute: typeof AuthenticatedEspaceIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace/utilisateurs': {
      id: '/_authenticated/espace/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/espace/utilisateurs'
      preLoaderRoute: typeof AuthenticatedEspaceUtilisateursRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/taches': {
      id: '/_authenticated/espace/taches'
      path: '/taches'
      fullPath: '/espace/taches'
      preLoaderRoute: typeof AuthenticatedEspaceTachesRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/commissions': {
      id: '/_authenticated/espace/commissions'
      path: '/commissions'
      fullPath: '/espace/commissions'
      preLoaderRoute: typeof AuthenticatedEspaceCommissionsRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/dossiers/': {
      id: '/_authenticated/espace/dossiers/'
      path: '/dossiers'
      fullPath: '/espace/dossiers/'
      preLoaderRoute: typeof AuthenticatedEspaceDossiersIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/compagnies/': {
      id: '/_authenticated/espace/compagnies/'
      path: '/compagnies'
      fullPath: '/espace/compagnies/'
      preLoaderRoute: typeof AuthenticatedEspaceCompagniesIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/clients/': {
      id: '/_authenticated/espace/clients/'
      path: '/clients'
      fullPath: '/espace/clients/'
      preLoaderRoute: typeof AuthenticatedEspaceClientsIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/dossiers/$id': {
      id: '/_authenticated/espace/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/espace/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedEspaceDossiersIdRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/contrats/$id': {
      id: '/_authenticated/espace/contrats/$id'
      path: '/contrats/$id'
      fullPath: '/espace/contrats/$id'
      preLoaderRoute: typeof AuthenticatedEspaceContratsIdRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/compagnies/$id': {
      id: '/_authenticated/espace/compagnies/$id'
      path: '/compagnies/$id'
      fullPath: '/espace/compagnies/$id'
      preLoaderRoute: typeof AuthenticatedEspaceCompagniesIdRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/clients/$id': {
      id: '/_authenticated/espace/clients/$id'
      path: '/clients/$id'
      fullPath: '/espace/clients/$id'
      preLoaderRoute: typeof AuthenticatedEspaceClientsIdRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
  }
}

interface AuthenticatedEspaceRouteChildren {
  AuthenticatedEspaceCommissionsRoute: typeof AuthenticatedEspaceCommissionsRoute
  AuthenticatedEspaceTachesRoute: typeof AuthenticatedEspaceTachesRoute
  AuthenticatedEspaceUtilisateursRoute: typeof AuthenticatedEspaceUtilisateursRoute
  AuthenticatedEspaceIndexRoute: typeof AuthenticatedEspaceIndexRoute
  AuthenticatedEspaceClientsIdRoute: typeof AuthenticatedEspaceClientsIdRoute
  AuthenticatedEspaceCompagniesIdRoute: typeof AuthenticatedEspaceCompagniesIdRoute
  AuthenticatedEspaceContratsIdRoute: typeof AuthenticatedEspaceContratsIdRoute
  AuthenticatedEspaceDossiersIdRoute: typeof AuthenticatedEspaceDossiersIdRoute
  AuthenticatedEspaceClientsIndexRoute: typeof AuthenticatedEspaceClientsIndexRoute
  AuthenticatedEspaceCompagniesIndexRoute: typeof AuthenticatedEspaceCompagniesIndexRoute
  AuthenticatedEspaceDossiersIndexRoute: typeof AuthenticatedEspaceDossiersIndexRoute
}

const AuthenticatedEspaceRouteChildren: AuthenticatedEspaceRouteChildren = {
  AuthenticatedEspaceCommissionsRoute: AuthenticatedEspaceCommissionsRoute,
  AuthenticatedEspaceTachesRoute: AuthenticatedEspaceTachesRoute,
  AuthenticatedEspaceUtilisateursRoute: AuthenticatedEspaceUtilisateursRoute,
  AuthenticatedEspaceIndexRoute: AuthenticatedEspaceIndexRoute,
  AuthenticatedEspaceClientsIdRoute: AuthenticatedEspaceClientsIdRoute,
  AuthenticatedEspaceCompagniesIdRoute: AuthenticatedEspaceCompagniesIdRoute,
  AuthenticatedEspaceContratsIdRoute: AuthenticatedEspaceContratsIdRoute,
  AuthenticatedEspaceDossiersIdRoute: AuthenticatedEspaceDossiersIdRoute,
  AuthenticatedEspaceClientsIndexRoute: AuthenticatedEspaceClientsIndexRoute,
  AuthenticatedEspaceCompagniesIndexRoute:
    AuthenticatedEspaceCompagniesIndexRoute,
  AuthenticatedEspaceDossiersIndexRoute: AuthenticatedEspaceDossiersIndexRoute,
}

const AuthenticatedEspaceRouteWithChildren =
  AuthenticatedEspaceRoute._addFileChildren(AuthenticatedEspaceRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEspaceRoute: typeof AuthenticatedEspaceRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEspaceRoute: AuthenticatedEspaceRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AssuranceEmprunteurRoute: AssuranceEmprunteurRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CoparentaliteRoute: CoparentaliteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
